# EDGE FUNCTIONS

[[edge_functions]]
	path = "/"
	function = "geo"

[dev]
	targetPort = 5173

# REDIRECTS

[[redirects]]
  from = "https://kazielmanawal.netlify.com/*"
  to = "https://kazielmanawal.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.kazielmanawal.netlify.com/*"
  to = "https://kazielmanawal.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://kazielmanawal.netlify.app/*"
  to = "https://kazielmanawal.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.kazielmanawal.netlify.app/*"
  to = "https://kazielmanawal.me/:splat"
  status = 301
  force = true

# HEADERS	

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/index.html"
  [headers.values]
		cache-control = '''
			max-age=86400,
      no-cache,
      public'''

[[headers]]
  for = "/sw.js"
  [headers.values]
		cache-control = '''
			max-age=86400,
			no-cache,
			public'''

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
		cache-control = '''
			max-age=86400,
			no-cache,
      public'''

[[headers]]
  for = "/.*\\.(png|svg|ico)$"
  [headers.values]
		cache-control = '''
			max-age=604800,
			public,
      stale-while-revalidate=86400'''

[[headers]]
  for = "/og.jpg"
  [headers.values]
		cache-control = '''
			max-age=604800,
			public,
      stale-while-revalidate=86400'''

[[headers]]
  for = "/*.woff2"
  [headers.values]
		cache-control = '''
			max-age=604800,
			public,
      stale-while-revalidate=86400'''

[[headers]]
  for = "/assets/*"
  [headers.values]
		cache-control = '''
			max-age=31536000,
			public,
      immutable'''